# Generated by Django 4.2 on 2026-01-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allowed_tenants',
            field=models.ManyToManyField(blank=True, help_text='Deixe em branco para liberar para todos os tenants.', related_name='allowed_videos', to='stream.tenant'),
        ),
    ]
