# Generated by Django 4.2 on 2026-01-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_video_allowed_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='allowed_tenants',
        ),
        migrations.AddField(
            model_name='video',
            name='blocked_tenants',
            field=models.ManyToManyField(blank=True, help_text='Marque os tenants que não devem ver esse vídeo.', related_name='blocked_videos', to='stream.tenant'),
        ),
    ]
