# Generated by Django 4.2 on 2026-01-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_remove_video_allowed_tenants_video_blocked_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='blocked_tenants',
            field=models.ManyToManyField(blank=True, help_text='Marque os tenants que não devem ver este vídeo.', related_name='blocked_videos', to='stream.tenant'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='stream.tenant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='stream.video')),
            ],
            options={
                'unique_together': {('tenant', 'video')},
            },
        ),
    ]
