# Generated by Django 4.2 on 2026-01-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_alter_video_blocked_tenants_alter_video_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rotate_180',
            field=models.BooleanField(default=False, help_text='Rotacione o vídeo em 180° durante a reprodução.'),
        ),
    ]
