# Generated by Django 4.2 on 2026-01-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_video_rotate_180'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(max_length=1024),
        ),
    ]
