# Generated by Django 4.2 on 2026-01-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_alter_video_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.TextField(max_length=2048),
        ),
    ]
