# Generated by Django 4.2 on 2026-01-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_video_episode_number_video_season_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('movie', 'Filmes'), ('series', 'Séries'), ('tv', 'TV')], default='movie', help_text='Classifique este conteúdo como filme, série ou canal de TV.', max_length=16),
        ),
    ]
