# Generated by Django 4.2 on 2026-01-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, choices=[('acao', 'Ação'), ('drama', 'Drama'), ('comedia', 'Comédia'), ('fantasia', 'Fantasia'), ('documentario', 'Documentário'), ('infantil', 'Infantil'), ('terror', 'Terror'), ('animacao', 'Animação'), ('romance', 'Romance'), ('outro', 'Outro')], help_text='Gênero principal (filmes e séries).', max_length=32),
        ),
    ]
