# Generated by Django 4.2 on 2026-01-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_video_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('movie', 'Filmes'), ('series', 'Séries'), ('tv', 'TV'), ('mininovela', 'Mininovela')], default='movie', help_text='Classifique este conteúdo como filme, série ou canal de TV.', max_length=16),
        ),
    ]
