# Generated by Django 4.2 on 2026-01-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='display_category',
            field=models.CharField(choices=[('series', 'Séries'), ('mininovela', 'Mininovelas')], default='series', help_text='Escolha onde esta série deve aparecer no catálogo.', max_length=16),
        ),
    ]
